# PySNMP SMI module. Autogenerated from smidump -f python CISCO-UNIFIED-COMPUTING-NOTIFS-MIB
# by libsmi2pysnmp-0.1.3 at Wed Apr  8 22:57:26 2015,
# Python version (2, 6, 6, 'final', 0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( ciscoMgmt, ) = mibBuilder.importSymbols("CISCO-SMI", "ciscoMgmt")
( cucsFaultAffectedObjectDn, cucsFaultAffectedObjectId, cucsFaultCode, cucsFaultCreationTime, cucsFaultDescription, cucsFaultId, cucsFaultIndex, cucsFaultLastModificationTime, cucsFaultOccur, cucsFaultProbableCause, cucsFaultSeverity, cucsFaultType, ) = mibBuilder.importSymbols("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultAffectedObjectDn", "cucsFaultAffectedObjectId", "cucsFaultCode", "cucsFaultCreationTime", "cucsFaultDescription", "cucsFaultId", "cucsFaultIndex", "cucsFaultLastModificationTime", "cucsFaultOccur", "cucsFaultProbableCause", "cucsFaultSeverity", "cucsFaultType")
( ciscoUnifiedComputingMIB, ciscoUnifiedComputingMIBObjects, ) = mibBuilder.importSymbols("CISCO-UNIFIED-COMPUTING-MIB", "ciscoUnifiedComputingMIB", "ciscoUnifiedComputingMIBObjects")
( Bits, Integer32, ModuleIdentity, MibIdentifier, NotificationType, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "NotificationType", "TimeTicks")

# Objects

ciscoUnifiedComputingMIBNotifs = ModuleIdentity((1, 3, 6, 1, 4, 1, 9, 9, 719, 0)).setRevisions(("2010-01-29 00:00",))
if mibBuilder.loadTexts: ciscoUnifiedComputingMIBNotifs.setOrganization("Cisco")
if mibBuilder.loadTexts: ciscoUnifiedComputingMIBNotifs.setContactInfo("Cisco Systems\nCustomer Service\n\nPostal: 170 West Tasman Drive\nSan Jose, CA  95134\nUSA\n\nTel: +1 800 553-NETS\n\nE-mail: savbu-snmp-dev@cisco.com")
if mibBuilder.loadTexts: ciscoUnifiedComputingMIBNotifs.setDescription("Fault traps (notifications) issued by the UCS system")

# Augmentions

# Notifications

cucsFaultActiveNotif = NotificationType((1, 3, 6, 1, 4, 1, 9, 9, 719, 0, 1)).setObjects(*(("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultDescription"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultProbableCause"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultOccur"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultCreationTime"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultLastModificationTime"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultType"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultAffectedObjectDn"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultCode"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultSeverity"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultAffectedObjectId"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultIndex"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultId"), ) )
if mibBuilder.loadTexts: cucsFaultActiveNotif.setDescription("This notification is generated by a UCS node whenever a fault\nis active and the fault state changes.")
cucsFaultClearNotif = NotificationType((1, 3, 6, 1, 4, 1, 9, 9, 719, 0, 2)).setObjects(*(("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultDescription"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultProbableCause"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultOccur"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultCreationTime"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultLastModificationTime"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultType"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultAffectedObjectDn"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultCode"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultSeverity"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultAffectedObjectId"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultIndex"), ("CISCO-UNIFIED-COMPUTING-FAULT-MIB", "cucsFaultId"), ) )
if mibBuilder.loadTexts: cucsFaultClearNotif.setDescription("This notification is generated by a UCS node whenever a fault\nis cleared.")

# Exports

# Module identity
mibBuilder.exportSymbols("CISCO-UNIFIED-COMPUTING-NOTIFS-MIB", PYSNMP_MODULE_ID=ciscoUnifiedComputingMIBNotifs)

# Objects
mibBuilder.exportSymbols("CISCO-UNIFIED-COMPUTING-NOTIFS-MIB", ciscoUnifiedComputingMIBNotifs=ciscoUnifiedComputingMIBNotifs)

# Notifications
mibBuilder.exportSymbols("CISCO-UNIFIED-COMPUTING-NOTIFS-MIB", cucsFaultActiveNotif=cucsFaultActiveNotif, cucsFaultClearNotif=cucsFaultClearNotif)

