name             'sensu-trapd'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures sensu-trapd'
long_description 'Installs/Configures sensu-trapd'
version          '0.1.0'

depends 'yum', '~> 3.0'
depends 'iaas-sensu-clients'